# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dac48b0925458455fdc36d35c7595d112699efea0fc91ea2de2af122f96b924c100c2e69a3ff250ee47a2968905454f14762e7e6f3f04dc9cd75e2b14e71d941

test:
  secret_key_base: 10be9d5a342fa3e0c03f411bdfabc4e5009e87319375c46545e5ee48db89bcab9a742697ee65e42ce455016491ad76ef633c118978b8710ef5d82ce650aaef8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
